//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class bank
{
    public int id { get; set; }
    public Nullable<double> value { get; set; }
    public Nullable<int> user_id { get; set; }
    public string BankName { get; set; }
    public string roleType { get; set; }
}

public partial class bank_account
{
    public int id { get; set; }
    public string bank_name { get; set; }
    public string bank_id { get; set; }
    public Nullable<double> daan { get; set; }
    public Nullable<double> mdeen { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<System.DateTime> datep { get; set; }
    public string typeRole { get; set; }
    public string title { get; set; }
}

public partial class category
{
    public int id { get; set; }
    public string name { get; set; }
    public string roleType { get; set; }
}

public partial class customer
{
    public int id { get; set; }
    public string name { get; set; }
    public Nullable<double> balance { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string address { get; set; }
    public string phone { get; set; }
    public string roleType { get; set; }
}

public partial class customer_account
{
    public int id { get; set; }
    public Nullable<int> customer_id { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<double> pay { get; set; }
    public Nullable<double> repay { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string title { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public Nullable<int> inv_id { get; set; }
    public string img { get; set; }
}

public partial class destroy_inv
{
    public int id { get; set; }
    public Nullable<int> prod_id { get; set; }
    public string prod_name { get; set; }
    public Nullable<int> inv_id { get; set; }
    public Nullable<int> stat { get; set; }
    public string roleType { get; set; }
    public Nullable<double> quant { get; set; }
    public Nullable<double> item_total { get; set; }
}

public partial class destroy_invoices
{
    public int id { get; set; }
    public Nullable<System.DateTime> date_destroy_inv { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<double> running_price { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public string roletype { get; set; }
    public Nullable<int> recycled_item { get; set; }
    public string recycled_item_name { get; set; }
    public Nullable<double> recycled_quantity { get; set; }
    public Nullable<int> rec_id { get; set; }
}

public partial class import
{
    public Nullable<int> id { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<int> importer_id { get; set; }
    public Nullable<double> discount { get; set; }
    public Nullable<double> Net_total { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public string importer_name { get; set; }
    public int add_id { get; set; }
    public string roleType { get; set; }
    public Nullable<double> payedvalue { get; set; }
}

public partial class import_items
{
    public int id { get; set; }
    public Nullable<int> imp_id { get; set; }
    public string prod_code { get; set; }
    public string prod_name { get; set; }
    public Nullable<double> quantity { get; set; }
    public Nullable<double> price { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<System.DateTime> ex_date { get; set; }
}

public partial class importer
{
    public int id { get; set; }
    public string name { get; set; }
    public Nullable<double> balance { get; set; }
    public string title { get; set; }
    public Nullable<double> value { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string address { get; set; }
    public string phone { get; set; }
    public string roleType { get; set; }
}

public partial class importer_account
{
    public int id { get; set; }
    public Nullable<int> importer_id { get; set; }
    public string importer_name { get; set; }
    public Nullable<double> daan { get; set; }
    public Nullable<double> mdeen { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string title { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public Nullable<int> inv_id { get; set; }
}

public partial class invoice
{
    public int id { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<int> customer_id { get; set; }
    public Nullable<double> discount { get; set; }
    public Nullable<double> Nettotal { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public string customer_name { get; set; }
    public string typeRole { get; set; }
    public string img { get; set; }
    public Nullable<int> casherid { get; set; }
    public string casherName { get; set; }
    public Nullable<double> payed { get; set; }
    public Nullable<int> inv_id { get; set; }
}

public partial class invoice_items
{
    public int id { get; set; }
    public Nullable<int> inv_id { get; set; }
    public string prod_code { get; set; }
    public string prod_name { get; set; }
    public Nullable<double> quantity { get; set; }
    public Nullable<double> price { get; set; }
    public Nullable<double> cost { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<double> NetTotal { get; set; }
}

public partial class payment
{
    public int id { get; set; }
    public string title { get; set; }
    public Nullable<double> value { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string notes { get; set; }
    public Nullable<int> inv_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public string roleType { get; set; }
    public string img { get; set; }
    public string type { get; set; }
}

public partial class return_items
{
    public int id { get; set; }
    public Nullable<int> return_id { get; set; }
    public string prod_code { get; set; }
    public string prod_name { get; set; }
    public Nullable<double> quantity { get; set; }
    public Nullable<double> price { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<int> status { get; set; }
    public string roleType { get; set; }
}

public partial class returninv
{
    public int id { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public Nullable<double> total { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public string roleType { get; set; }
    public Nullable<int> inv_id { get; set; }
}

public partial class SalesMen
{
    public int id { get; set; }
    public string name { get; set; }
    public string roleType { get; set; }
}

public partial class savee
{
    public int id { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string title { get; set; }
    public Nullable<double> daan { get; set; }
    public Nullable<double> mdeen { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public string item_id { get; set; }
    public string Operation_type { get; set; }
    public string roleType { get; set; }
}

public partial class stock
{
    public int id { get; set; }
    public string code { get; set; }
    public string name { get; set; }
    public Nullable<double> quantity { get; set; }
    public Nullable<double> min_quantity { get; set; }
    public Nullable<int> cat_id { get; set; }
    public string cat_name { get; set; }
    public Nullable<double> price { get; set; }
    public string size { get; set; }
    public Nullable<double> buy_price { get; set; }
    public string roleType { get; set; }
    public Nullable<double> perc_destroy { get; set; }
}

public partial class stock_destroy
{
    public int id { get; set; }
    public Nullable<int> product_id { get; set; }
    public string product_name { get; set; }
    public Nullable<double> quantity { get; set; }
    public Nullable<int> user_id { get; set; }
    public string user_name { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string typeRole { get; set; }
    public Nullable<int> id_item { get; set; }
}

public partial class users
{
    public int id { get; set; }
    public string name { get; set; }
    public string user_name { get; set; }
    public string password { get; set; }
    public string role { get; set; }
    public string typeRole { get; set; }
}
