//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class FactoryDBEntities : DbContext
{
    public FactoryDBEntities()
        : base("name=FactoryDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<bank> bank { get; set; }
    public virtual DbSet<bank_account> bank_account { get; set; }
    public virtual DbSet<category> category { get; set; }
    public virtual DbSet<customer> customer { get; set; }
    public virtual DbSet<customer_account> customer_account { get; set; }
    public virtual DbSet<import> import { get; set; }
    public virtual DbSet<import_items> import_items { get; set; }
    public virtual DbSet<importer> importer { get; set; }
    public virtual DbSet<importer_account> importer_account { get; set; }
    public virtual DbSet<invoice> invoice { get; set; }
    public virtual DbSet<invoice_items> invoice_items { get; set; }
    public virtual DbSet<payment> payment { get; set; }
    public virtual DbSet<return_items> return_items { get; set; }
    public virtual DbSet<returninv> returninv { get; set; }
    public virtual DbSet<savee> savee { get; set; }
    public virtual DbSet<stock> stock { get; set; }
    public virtual DbSet<users> users { get; set; }
    public virtual DbSet<SalesMen> SalesMen { get; set; }
    public virtual DbSet<stock_destroy> stock_destroy { get; set; }
    public virtual DbSet<destroy_inv> destroy_inv { get; set; }
    public virtual DbSet<destroy_invoices> destroy_invoices { get; set; }
}
